services:
  app:
    image: ghcr.io/shmandalf/fast-atomic-flow:latest
    container_name: atomic-flow-app
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-9501}:${SERVER_PORT:-9501}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # < 10Mb
        max-file: "3"   # Keep 3 files max
    networks:
      - atomic-network

networks:
  atomic-network:
    driver: bridge
