name: PHPSatan Code Inferno / Quality Control

on: [push, pull_request]

jobs:
  build:
    name: Burning bugs at Level 5
    runs-on: ubuntu-latest

    steps:
      - name: Summoning the Source Code
        uses: actions/checkout@v4

      - name: Lighting the PHP 8.4 Altar
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: swoole, pcntl, posix
          coverage: none

      - name: Gathering Sacrificial Dependencies
        run: composer install --no-progress --no-suggest

      - name: Executing the Ritual (PHPStan)
        run: composer analyze
